[package]
name = "glulx-terp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.2.0"
byteorder = "1.5.0"
num_enum = "0.7.2"
